# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AhTZ3rZqBEnp7MJ-kzI9NZMmcHYQ8Qrf
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

#read data from the data set
df = pd.read_csv("/content/Titanic-Dataset.csv")

#print empty values in a column
print(df[df['Age'].isnull()])

print(df[df['Embarked'].isnull()])

#impute age with median
df['Age'] = df['Age'].fillna(df['Age'].median())

#impute embarked with mode
df["Embarked"]= df['Embarked'].fillna(df['Embarked'].mode()[0])

#drop irrelevant cols
irrelavent_columns = ['Cabin']
df.drop(columns = irrelavent_columns,inplace = True)

#print missing values
print("\nMissing values after handling:")
print(df.isnull().sum())

#lower_bound using IQR
Q1 = df['Fare'].quantile(0.25)
Q3 = df['Fare'].quantile(0.75)

IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
df['Fare'] = np.where(df['Fare'] < lower_bound,lower_bound,df['Fare'])

#upper_bound using IQR
upper_bound = Q3 + 1.5 * IQR
df['Fare'] = np.where(df['Fare'] > upper_bound,upper_bound,df['Fare'])

#one-hot encoding
df = pd.get_dummies(df,columns = ['Sex','Embarked'], drop_first = True)

# Label encoding for remaining categorical columns
label_encoder = LabelEncoder()
categorical_cols = df.select_dtypes(include=['object']).columns

for col in categorical_cols:
    df[col] = label_encoder.fit_transform(df[col])

#split data
x  = df.drop('Survived',axis = 1)
y = df['Survived']
x_train,x_temp,y_train,y_temp = train_test_split(x,y,test_size = 0.30,random_state = 30)
x_validate,x_test,y_validate,y_test = train_test_split(x_temp,y_temp,test_size = 0.50,random_state = 30)

print("\nDataset Split Shapes")
print("---------------------")
print("Training Set   :", x_train.shape, y_train.shape)
print("Validation Set :", x_validate.shape, y_validate.shape)
print("Testing Set    :", y_test.shape, y_test.shape)